# gadget.param : changa.param
g2c_name_dict = {\
    'CritPhysDensity'               :'',\
    'MaxSfrTimescale'               :'',\
    'CritOverDensity'               :'',\
    'TempSupernova'                 :'',\
    'TempClouds'                    :'',\
    'FactorSN'                      :'',\
    'FactorEVP'                     :'',\
    'WindEfficiency'                :'',\
    'WindEnergyFraction'            :'',\
    'WindFreeTravelDensFac'         :'',\
    'WindFreeTravelMaxTimeFactor'   :'',\
    'FactorForSofterEQS'            :'',\
    'SofteningGas'                  :'',\
    'SofteningHalo'                 :'',\
    'SofteningDisk'                 :'',\
    'SofteningBulge'                :'',\
    'SofteningStars'                :'',\
    'SofteningBndry'                :'',\
    'InitCondFile'                  :'achInFile',\
    'SnapshotFileBase'              :'achOutFile',\
    'EnergyFile'                    :'',\
    'InfoFile'                      :'',\
    'TimingsFile'                   :'',\
    'CpuFile'                       :'',\
    'TimebinFile'                   :'',\
    'RestartFile'                   :'',\
    'OutputDir'                     :'',\
    'TimeLimitCPU'                  :'iWallRunTime',\
    'ResubmitOn'                    :'',\
    'ResubmitCommand'               :'',\
    'ICFormat'                      :'',\
    'SnapFormat'                    :'',\
    'NumFilesPerSnapshot'           :'',\
    'NumFilesWrittenInParallel'     :'',\
    'ComovingIntegrationOn'         :'bComove',\
    'CoolingOn'                     :'bGasCooling',\
    'StarformationOn'               :'bStarForm',\
    'TimeBegin'                     :'iStartStep',\
    'TimeMax'                       :'',\
    'Omega0'                        :'dOmega0',\
    'OmegaLambda'                   :'dLambda',\
    'OmegaBaryon'                   :'dOmegab',\
    'HubbleParam'                   :'dHubble0',\
    'BoxSize'                       :'dPeriod',\
    'PeriodicBoundariesOn'          :'bPeriodic',\
    'OutputListOn'                  :'',\
    'OutputListFilename'            :'',\
    'TimeBetSnapshot'               :'iOutInterval',\
    'TimeOfFirstSnapshot'           :'',\
    'CpuTimeBetRestartFile'         :'',\
    'TimeBetStatistics'             :'iLogInterval',\
    'TypeOfTimestepCriterion'       :'',\
    'ErrTolIntAccuracy'             :'dEta',\
    'MaxSizeTimestep'               :'dDelta',\
    'MinSizeTimestep'               :'',\
    'MaxRMSDisplacementFac'         :'',\
    'ErrTolTheta'                   :'dTheta',\
    'TypeOfOpeningCriterion'        :'',\
    'ErrTolForceAcc'                :'',\
    'TreeDomainUpdateFrequency'     :'',\
    'ArtBulkViscConst'              :'dConstAlpha',\
    'InitGasTemp'                   :'',\
    'MinGasTemp'                    :'',\
    'CourantFac'                    :'dEtaCourant',\
    'DesNumNgb'                     :'nSmooth',\
    'MaxNumNgbDeviation'            :'',\
    'PartAllocFactor'               :'',\
    'BufferSize'                    :'',\
    'MaxMemSize'                    :'',\
    'UnitLength_in_cm'              :'dKpcUnit',\
    'UnitMass_in_g'                 :'dMsolUnit',\
    'UnitVelocity_in_cm_per_s'      :'',\
    'GravityConstantInternal'       :'',\
    'MinGasHsmlFractional'          :'dhMinOverSoft',\
    'SofteningGasMaxPhys'           :'',\
    'SofteningBulgeMaxPhys'         :'',\
    'SofteningStarsMaxPhys'         :'',\
    'SofteningBndryMaxPhys'         :'',\
    'SofteningHaloMaxPhys'          :'',\
    'SofteningDiskMaxPhys'          :'',\
        }

