# gadget.param : changa.param
gad_to_cha_dict = {\
    'CritPhysDensity'                       :'placeholder1',\
    'MaxSfrTimescale'                       :'placeholder2',\
    'CritOverDensity'                       :'placeholder3',\
    'TempSupernova'                         :'placeholder4',\
    'TempClouds'                            :'placeholder5',\
    'FactorSN'                              :'placeholder6',\
    'FactorEVP'                             :'placeholder7',\
    'WindEfficiency'                        :'placeholder8',\
    'WindEnergyFraction'                    :'',\
    'WindFreeTravelDensFac'                 :'',\
    'WindFreeTravelMaxTimeFactor'           :'',\
    'FactorForSofterEQS'                    :'',\
    'SofteningGas'                          :'',\
    'SofteningHalo'                         :'',\
    'SofteningDisk'                         :'',\
    'SofteningBulge'                        :'',\
    'SofteningStars'                        :'',\
    'SofteningBndry'                        :'',\
    'InitCondFile'                          :'',\
    'SnapshotFileBase'                      :'',\
    'EnergyFile'                            :'',\
    'InfoFile'                              :'',\
    'TimingsFile'                           :'',\
    'CpuFile'                               :'',\
    'TimebinFile'                           :'',\
    'RestartFile'                           :'',\
    'OutputDir'                             :'',\
    'TimeLimitCPU'                          :'',\
    'ResubmitOn'                            :'',\
    'ResubmitCommand'                       :'',\
    'ICFormat'                              :'',\
    'SnapFormat'                            :'',\
    'NumFilesPerSnapshot'                   :'',\
    'NumFilesWrittenInParallel'             :'',\
    'ComovingIntegrationOn'                 :'',\
    'CoolingOn'                             :'',\
    'StarformationOn'                       :'',\
    'TimeBegin'                             :'',\
    'TimeMax'                               :'',\
    'Omega0'                                :'',\
    'OmegaLambda'                           :'',\
    'OmegaBaryon'                           :'',\
    'HubbleParam'                           :'',\
    'BoxSize'                               :'',\
    'PeriodicBoundariesOn'                  :'',\
    'OutputListOn'                          :'',\
    'OutputListFilename'                    :'',\
    'TimeBetSnapshot'                       :'',\
    'TimeOfFirstSnapshot'                   :'',\
    'CpuTimeBetRestartFile'                 :'',\
    'TimeBetStatistics'                     :'',\
    'TypeOfTimestepCriterion'               :'',\
    'ErrTolIntAccuracy'                     :'',\
    'MaxSizeTimestep'                       :'',\
    'MinSizeTimestep'                       :'',\
    'MaxRMSDisplacementFac'                 :'',\
    'ErrTolTheta'                           :'',\
    'TypeOfOpeningCriterion'                :'',\
    'ErrTolForceAcc'                        :'',\
    'TreeDomainUpdateFrequency'             :'',\
    'ArtBulkViscConst'                      :'',\
    'InitGasTemp'                           :'',\
    'MinGasTemp'                            :'',\
    'CourantFac'                            :'',\
    'DesNumNgb'                             :'',\
    'MaxNumNgbDeviation'                    :'',\
    'PartAllocFactor'                       :'',\
    'BufferSize'                            :'',\
    'MaxMemSize'                            :'',\
    'UnitLength_in_cm'                      :'',\
    'UnitMass_in_g'                         :'',\
    'UnitVelocity_in_cm_per_s'              :'',\
    'GravityConstantInternal'               :'',\
    'MinGasHsmlFractional'                  :'',\
    'SofteningGasMaxPhys'                   :'',\
    'SofteningBulgeMaxPhys'                 :'',\
    'SofteningStarsMaxPhys'                 :'',\
    'SofteningBndryMaxPhys'                 :'',\
    'SofteningHaloMaxPhys'                  :'',\
    'SofteningDiskMaxPhys'                  :'',\
                  }
